name: home_care_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  table_calendar: ^2.2.1
  fancy_bottom_navigation: ^0.1.0
  curved_navigation_bar: ^0.3.1
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/mans_img.jpeg
    - assets/images/runing.png
    - assets/images/meditaion.png
    - assets/images/2.png
    - assets/images/female_above40.jpg
    - assets/images/powered_by.png
    - assets/images/logo.png
    - assets/images/marie_img.jpeg
    - assets/images/lynda.jpg
    - assets/images/Michael_img.jpg
    - assets/images/michael.jpg
    - assets/images/blood_1.png
    - assets/images/heartrate.png
    - assets/images/temprature.png
    - assets/images/splash1.jpg
    - assets/images/care1.png
    - assets/images/care-2.png
    - assets/images/care-3.png

  fonts:

    - family: Roboto Medium
      fonts:
        - asset: fonts/Roboto-Medium.ttf

    - family: Roboto Regular
      fonts:
        - asset: fonts/Roboto-Regular.ttf

    - family: Roboto Thin

      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 700
